Iter9
javaman/go-metrics pull request #10
Opened 2023-05-30 08:09 UTC by javaman

2023-05-30 22:10 UTC, maxlyaptsev requested changes

2023-05-30 22:10 UTC, maxlyaptsev commented on internal/repository/repository.go
> +	data, err := json.MarshalIndent(m, "", "   ")
нужно ли сохранять в файл текст с отступами?

2023-05-30 22:10 UTC, maxlyaptsev commented on internal/services/services.go
> +		retVal.ID = m.ID
выше создается структура, почему бы сразу ее не заполнить?

2023-05-30 22:10 UTC, maxlyaptsev commented on internal/services/services.go
> +		}
аналогично в других местах
```suggestion
		return nil, ErrIDNotFound
		
```

2023-05-30 22:10 UTC, maxlyaptsev commented on cmd/agent/main.go
> +	j.Delta = &v
```suggestion
	j := &model.Metrics{
	   ID: m.name()
	   // ...
	}

```

здесь и ниже - лучше сразу заполнять стурктуру

2023-05-30 22:10 UTC, maxlyaptsev commented on cmd/server/main.go
> +	if cfg.Restore {
https://github.com/sau00/uber-go-guide-ru/blob/master/style.md#Излишние-else

2023-05-30 22:10 UTC, maxlyaptsev commented on cmd/server/main.go
> +	} else {
https://github.com/sau00/uber-go-guide-ru/blob/master/style.md#Излишние-else

2023-05-30 22:10 UTC, maxlyaptsev commented on internal/services/services.go
> +	case "counter":
может стоит разделить функцонал counter и gauge на два отдельных метода?

2023-05-30 22:10 UTC, maxlyaptsev commented on internal/services/services.go
> +	case "counter":
аналогично, кажется в одном методе сразу два. Если приходится использовать switch или много if'ов - это признак что структура неверная

2023-05-31 04:32 UTC, javaman commented on internal/handlers/handlers.go
> +			defer func() {
Я этот код из эховского middleware стащил. Без него правильно не работало. 
Если ответ пустой - то надо явно менять.
Потому что если какая то ошибка, например урл ни на что не мапится. В аутпут пишется еррор из потрохов что попытка перезаписать статус ответа, flated уже закрыт. И всегда возвращается 200. 
Пришлось посмотерть как там мидлваре работает и найти тот код из за чего у меня не работало и дописать тут.

2023-05-31 05:16 UTC, javaman commented on cmd/server/main.go
> +	if cfg.Restore {
Тут это непременимо вроде?  В разных ветвях разная логика.

2023-05-31 05:17 UTC, javaman commented on cmd/server/main.go
> +	} else {
кажется то же - по ссылке не про этот случай

2023-05-31 05:20 UTC, javaman commented on internal/repository/repository.go
> +	data, err := json.MarshalIndent(m, "", "   ")
почему бы нет в данном случае?  удобно читать в целях мониторинга работы приложения. 

Минусов никаких нет.

2023-05-31 06:17 UTC, javaman commented on internal/services/services.go
> +	case "counter":
добавил два метода

2023-05-31 09:03 UTC, javaman commented on internal/services/services.go
> +	case "counter":
поделил

2023-05-31 11:18 UTC, maxlyaptsev requested changes

2023-05-31 11:18 UTC, maxlyaptsev commented on internal/services/services.go
>  	if value, ok := dm.storage.GetCounter(name); ok {
нам точно нужны эти условия? Что если вернуть value как 0 в случае его отсутствия - тогда можно будет просто прибавить новое значение

2023-05-31 11:18 UTC, maxlyaptsev commented on internal/services/services.go
> +	dm.saveCounter(name, v)
а зачем два saveCounter? 
А еще есть saveCounterStruct - чем они все отличаются?

2023-05-31 11:37 UTC, javaman commented on internal/middleware/middleware.go
> +			defer func() {
Без него тесты не работали, посмотрел как в middleware  echo  это реализовано, там случай с пустым телом отрабатывается таким образом. Потому если закрыть пустой зипованый стрим, там будут служебные символы. Которые уйдут в ответ на запрос.  
 Я столкнулся с этим же
[https://github.com/labstack/echo/issues/426#issue-142135198](url)

2023-05-31 11:53 UTC, javaman commented on internal/services/services.go
> +	dm.saveCounter(name, v)
так это, ты же попросил отдельные методы сделать на предыдущей итерации.
один принимает называние и значение второй структуру с метрикой

2023-05-31 12:04 UTC, javaman commented on internal/services/services.go
>  	if value, ok := dm.storage.GetCounter(name); ok {
о, точно

2023-05-31 12:04 UTC, javaman commented on internal/handlers/handlers.go
> +		} else {
пропустил,

2023-05-31 12:05 UTC, javaman commented on cmd/server/main.go
> +		storage = repository.MakeStorageFlushedOnEachCall(storage, cfg.FileStoragePath)
да, действительно. понял о чем речь.

2023-05-31 18:22 UTC, maxlyaptsev approved these changes

2023-05-31 18:22 UTC, maxlyaptsev commented on internal/repository/repository.go
> +	data, err := json.MarshalIndent(m, "", "   ")
1 - при чтении легко отфроматировать и вывести как хочется
2 - строка удобней для хранения и поиска данных (grep)
3 - парсинг данных гараздо удобнее делать в одну строку (logstash)
4 - если решим читать построчно - как будем работать с такой записью?

2023-05-31 18:22 UTC, maxlyaptsev commented on internal/services/services.go
> +func (dm *defaultMetricsService) saveGaugeStruct(m *model.Metrics) (*model.Metrics, error) {
```suggestion
func (dm *defaultMetricsService) saveGauge(m *model.Metrics) (*model.Metrics, error) {
```
Struct не несет нагрузки

2023-05-31 18:22 UTC, maxlyaptsev commented on internal/services/services.go
> +	case "counter":
Большое количество swith и if лучше избегать. Чаще всего проблема в архитектуре. В данном случае почему просто не взывать сразу нужный метод?  

Можно почитать об этом в книге «Чистый код» Роберт Мартин

2023-05-31 18:22 UTC, maxlyaptsev commented on internal/handlers/handlers.go
> +	e.Use(middleware.RequestLoggerWithConfig(middleware.RequestLoggerConfig{
Все еще очень рекомендую перенести логирование в middleware

2023-05-31 18:22 UTC, maxlyaptsev commented on internal/handlers/handlers.go
> +func New(service services.MetricsService) *echo.Echo {
хорошо бы вынести в отдельынй файлик router - можно и в отдельный пакет. Тяжело искать роутер в пакете handerls, но если здесь будет лежать файл router.go - сразу будет понятно что он там

2023-05-31 18:22 UTC, maxlyaptsev commented on cmd/server/main.go
> +		storage = repository.NewInMemoryStorageFromFile(cfg.FileStoragePath)
Все еще рекомендую сначала создать стурктуру, а потом в случае если есть имя файла - наполнить ее данными. Но не создавать два конструктора (комент выше)

2023-06-01 03:38 UTC, merged