Iter13
javaman/go-metrics pull request #15
Opened 2023-06-08 15:57 UTC by javaman

2023-06-09 08:50 UTC, maxlyaptsev commented
<img width="710" alt="image" src="https://github.com/javaman/go-metrics/assets/10906726/33ccbf28-7574-4146-a0ab-aaa8808d4829">
Не увидел реализации ретраев (может не заметил)

2023-06-09 08:51 UTC, maxlyaptsev requested changes

2023-06-09 08:51 UTC, maxlyaptsev commented on internal/handlers/routes.go
> +	e.Use(mymiddleware.Decompress)
лучше сделать одной мидлварой

2023-06-09 08:51 UTC, maxlyaptsev commented on internal/repository/db.go
> +func query(tx *sql.Tx, id string, mtype string) (int64, float64, error) {
кажется это лишние функции - вызвать их нельзя, логически это по сути часть одной функции, но разделенный на две части. Не особо понял цель. А еще название query не очень удачное - очень общее

2023-06-09 08:51 UTC, maxlyaptsev commented on internal/repository/db.go
> +	_, value, err := query(tx, name, "gauge")
не понятно для чего здесь транзакция, тут только один запрос , ниже аналогично

2023-06-09 08:51 UTC, maxlyaptsev commented on internal/repository/db.go
> +	queryAll(tx, "gauge", func(id string, delta int64, value float64) {
а если ошибка?

2023-06-09 08:51 UTC, maxlyaptsev commented on internal/services/services.go
> +		case m.MType == "counter" && len(m.ID) > 0 && m.Delta != nil:
можно у структуры model.Metrics создать метод, например isDeltaCounter и перенести туда эту хрупкую логику (кажется тут можно что-то порефакторить и случайно поломать)

2023-06-09 08:51 UTC, maxlyaptsev commented on cmd/server/main.go
> +	storage, ping := repository.NewDatabaseStorage(cfg.DBDsn)
репозиторий это уже уровень приложения, он не должен знать о реализации бд, лучше сделать конект где-то здесь, и прокинуть уже готовую сущность для работы с бд

2023-06-09 08:51 UTC, maxlyaptsev commented on internal/services/services.go
> +	ping    func() error
это очень странная история -  а почему просто не вызвать метод ping у репозитория?
Но точно не в сервисе с метриками, работоспособность базы данных вряд ли его ответственность

2023-06-09 08:51 UTC, maxlyaptsev commented on internal/services/services.go
> +func NewMetricsService(repository repository.Storage, ping func() error) *defaultMetricsService {
этот метод должен быть на самом верху - сначала константы, интерфейсы и структура, потом его конструктор и только после его методы

2023-06-09 08:51 UTC, maxlyaptsev commented on internal/config/config.go
> +	//flag.StringVar(&conf.DBDsn, "d", "user=postgres password=iddqd123 host=localhost database=postgres sslmode=disable", "Подключение к БД")
```suggestion
```

2023-06-13 16:08 UTC, maxlyaptsev requested changes

2023-06-13 16:08 UTC, maxlyaptsev commented on internal/handlers/handlers.go
> +func Ping(ping func() error) func(echo.Context) error {
как вариант можем использовать Pinger интерфейс - он есть в стандартных либах даже
так все таки выглядит костыльненько

2023-06-13 16:08 UTC, maxlyaptsev commented on internal/handlers/routes.go
> +	e.GET("/ping", Ping(ping))
а если не ping прокидывать, а service - у него уже вызывать метод нужный - service.Storage.Ping() ?

2023-06-13 16:08 UTC, maxlyaptsev commented on internal/repository/db.go
> +	var value float64
мы же можем создать стурктуру и сканить в нее, зачем отдельные переменные?

2023-06-13 16:08 UTC, maxlyaptsev commented on internal/repository/db.go
> +func query(queryFunc func(string, ...any) (*sql.Rows, error), queryString string, consumer func(string, string, int64, float64) bool, args ...any) error {
я что-то даже не смог прочитать где тут аругменты и что возваращает функция. Такие обертки на самом деле особо смысла не умеют. Понадобится чуть другой метод сделать и придется переписыать. Да и сильно компактней не делает запрос (не уверен в чем была цель)

Лучше использовать сторонние библиотеки - мне вот нравится https://github.com/jmoiron/sqlx, обычно везде использую

2023-06-14 15:38 UTC, javaman commented on internal/repository/db.go
> +	var value float64
тут переменными можно обойтись

2023-06-14 21:02 UTC, maxlyaptsev requested changes

2023-06-14 21:02 UTC, maxlyaptsev commented on internal/repository/db.go
> +func (d *databaseStorage) get(id string, mtype string) (int64, float64, bool, error) {
неправильно возвращать столько значений. Вот я смотрю и у меня нет идей что тут первый аргумент, второй и третий. Лучше упаковывать в структуры

2023-06-14 21:02 UTC, maxlyaptsev commented on internal/repository/db.go
> +	d.getAll(model.Gauge, func(id string, delta int64, value float64) bool {
если честно, я не понимаю что здесь происходит. Давай просто вызовем метод - передадим аргументы, сделаем запрос и вернем результат.

2023-06-14 21:02 UTC, maxlyaptsev commented on internal/repository/db.go
> +func (d *databaseStorage) save(id string, mtype string, delta int64, value float64) error {
```suggestion
func (d *databaseStorage) save(metric Metric) error {
```
аналогично, очень много непонятных значений - есть delta, а есть value - без конекста не понятно в чем тут разница

2023-06-14 21:02 UTC, maxlyaptsev commented on internal/repository/db.go
> +func (d *databaseStorage) getAll(mtype string, consumer func(string, int64, float64) bool) error {
давай договоримся никогда не передавать функции в аргументы. Очень редко когда это оправдано. Такой код очень неочивидный и практически нечитаем
```suggestion
func (d *databaseStorage) getAll(mtype string) ([]Metric, error) {
```

2023-06-14 21:02 UTC, maxlyaptsev commented on internal/repository/db.go
> +	tx *sql.Tx
если будут два одновременных запроса, то эта транзакция перетрется и будет дедлок

2023-06-14 21:02 UTC, maxlyaptsev commented on internal/repository/db.go
> +		if err == nil || !errors.As(err, &netError) || pgconn.SafeToRetry(err) {
```suggestion
		if err == nil || !errors.As(err, &netError) || !pgconn.SafeToRetry(err) {
```

2023-06-14 21:02 UTC, maxlyaptsev commented on internal/repository/db.go
> +func retry(f func() error) error {
а если нужно будет ретрай другой функции сделать?

2023-06-15 02:16 UTC, javaman commented on internal/repository/db.go
> +	tx *sql.Tx
нет.

2023-06-15 02:23 UTC, javaman commented on internal/repository/db.go
> +func retry(f func() error) error {
?

2023-06-15 16:11 UTC, maxlyaptsev commented on internal/repository/db.go
> +	tx *sql.Tx
увидел, что для транзакции создается отдельная структура, ок
Но это не очень очевидно, поэтому и вызывает вопросы

2023-06-15 16:17 UTC, maxlyaptsev commented on internal/repository/db.go
> +func retry(f func() error) error {
этот retry принимает в себя конкетную функцию. Переиспользовать соответственно его нельзя.  А если нельзя переиспользовать, зачем выносить в отдельный метод?

Но вообще ретраи ближе к слою логики сервиса. Я бы вынес на слой выше чтобы явно видеть что есть повторные запросы, или из простых решений сделать отдельные методы WithRetry куда передавать настройки ретрая из конфига. 

А так ретраи неявные и сразу не видно что запросов может быть несколько, а не один

2023-07-14 07:14 UTC, closed without merging