Iter5
javaman/go-metrics pull request #6
Opened 2023-05-09 15:13 UTC by javaman

2023-05-10 12:13 UTC, maxlyaptsev requested changes

2023-05-10 12:13 UTC, maxlyaptsev commented on cmd/agent/main.go
> +func (m CounterMeasure) send(to MeasureDestination) {
save было бы более подходящим названием т.к. метрики на этом этапе еще не отправляются

2023-05-10 12:13 UTC, maxlyaptsev commented on cmd/agent/main.go
> +	mb.buffer = append(mb.buffer, m)
кажется разделять на такое количество функций уже не нужно - они становятся однострочными и чтобы понять одно логическое действие приходится переходить через несколько. 
captureMetrics -> send -> saveCounter -> save

2023-05-10 12:18 UTC, maxlyaptsev requested changes

2023-05-10 12:18 UTC, maxlyaptsev commented on cmd/agent/main.go
> +	address := flag.String("a", "localhost:8080", "Адрес сервера")
получение конфигов можно вынести в отдельный файл и положить его рядом - функция станет проще для чтения

2023-05-10 12:19 UTC, maxlyaptsev commented on cmd/agent/main.go
> +	if value, ok := os.LookupEnv("REPORT_INTERVAL"); ok {
nit если использовать строронний env пакет и для конфигурации использовать структуру, можно хорошо сократить код и сделать его понятней

2023-05-13 15:06 UTC, javaman commented on cmd/server/main.go
> +	e.GET("/value/counter/:measureName", valueCounter(storage))
Я попробовал по другом сделать, в итоге вернулся как было

2023-05-14 16:39 UTC, maxlyaptsev requested changes

2023-05-14 16:39 UTC, maxlyaptsev commented on cmd/server/main.go
>  package main
Пакеты разделены, но лежать они должны в internal директории, а не в с cmd
Тут можно почитать подробнее
https://github.com/golang-standards/project-layout/blob/master/README_ru.md#cmd

Рекомендую еще раз почитать урок "Структура проекта" в начале первого спринта, там хорошо расписано где должны располагаться файлы. Вот пример, который там приведен

<img width="752" alt="image" src="https://github.com/javaman/go-metrics/assets/10906726/ad3e386f-2cbc-4558-8f17-c5fe25a84df0">

2023-05-14 21:18 UTC, maxlyaptsev commented on cmd/server/main.go
> +	e.GET("/", handlers.ListAll(service))
роутер лучше тоже перенести в internal, а здесь сделать только его получение

2023-05-14 21:18 UTC, maxlyaptsev approved these changes

2023-05-15 05:24 UTC, merged